@host = localhost
@port = 4000

@

### new user
POST http://{{host}}:{{port}}/api/auth/new HTTP/1.1
Content-Type: application/json

{
    "name": "Ricardo",
    "email": "liker251281@gmail.com",
    "password": "20ri8125"
}

### login
POST http://{{host}}:{{port}}/api/auth/ HTTP/1.1
Content-Type: application/json

{
    "email": "liker251281@gmail.com",
    "password": "20ri8125"
}

### renew token
GET http://{{host}}:{{port}}/api/auth/renew HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MzdlZjU4OGE1NTQxNGJmZjJjNjgzOTEiLCJuYW1lIjoiUmljYXJkbyIsImlhdCI6MTY2OTI2ODYzNCwiZXhwIjoxNjY5Mjc1ODM0fQ.8QV_Hl3EqVVg7sfgMO4kKLe8UtJ-FbNieZMWFYK30T0